- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get-helm-3.sh
    mode: '0755'

- name: Run Helm install script
  command: /tmp/get-helm-3.sh
  become: true

- name: Ensure helm is in PATH
  command: helm version
  register: helm_check
  changed_when: false
