- name: Ensure mount directory exists
  file:
    path: "{{ mount_base }}/mediafiles"
    state: directory
    owner: k8smedia
    group: k8smedia
    mode: '0755'

- name: Ensure NFS mount in fstab and mounted
  mount:
    path: "{{ mount_base }}/mediafiles"
    src: "{{ nfs_server }}:{{ nfs_share }}"
    fstype: nfs
    opts: rw,sync,hard,intr,noatime,vers=4
    state: mounted
