- name: Install NFS client
  apt:
    name: nfs-common
    state: present

- name: Create mount directory for Mediafiles
  file:
    path: "{{ mount_base }}/mediafiles"
    state: directory
    owner: k8smedia
    group: k8smedia
    mode: '0755'

