all:
  vars:
    ansible_python_interpreter: /opt/k8s-venv/bin/python
    mount_base: /mnt
  children:
    master:
      hosts:
        hpmini5:
          ansible_host: 10.24.24.5
          ansible_user: k8smedia
    workers:
      hosts:
        hpmini6:
          ansible_host: 10.24.24.6
          ansible_user: k8smedia
        hpmini7:
          ansible_host: 10.24.24.7
          ansible_user: k8smedia
