- name: Create namespace for Cert-Manager
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: cert-manager
    state: present

- name: Add Jetstack Helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install Cert-Manager via Helm
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "v1.15.3"
    release_namespace: cert-manager
    values:
      installCRDs: true
    state: present

- name: Apply ClusterIssuer for Let's Encrypt
  kubernetes.core.k8s:
    state: present
    namespace: cert-manager
    template: "{{ role_path }}/templates/clusterissuer-letsencrypt.yaml.j2"

- name: Apply internal CA ClusterIssuer
  kubernetes.core.k8s:
    state: present
    namespace: cert-manager
    template: "{{ role_path }}/templates/clusterissuer-ca.yaml.j2"

- name: Create wildcard certificate for meabi.org
  kubernetes.core.k8s:
    state: present
    namespace: cert-manager
    template: "{{ role_path }}/templates/certificate-meabi.yaml.j2"

- name: Create wildcard certificate for home.meabi.org
  kubernetes.core.k8s:
    state: present
    namespace: cert-manager
    template: "{{ role_path }}/templates/certificate-home-meabi.yaml.j2"
