k3s_ingresses:
  - name: longhorn-ui
    namespace: longhorn-system
    host: longhorn.portal.meabi.org
    service: longhorn-frontend
    port: 80

  - name: pihole
    namespace: pihole
    host: pihole.meabi.org
    service: pihole
    port: 80

  - name: plex
    namespace: media
    host: plex.portal.meabi.org
    service: plex
    port: 32400
    
plex:
  namespace: media
  image: lscr.io/linuxserver/plex:latest
  claim_size: 20Gi
  timezone: "America/Mexico_City"
  puid: "1000"
  pgid: "1000"
  data_path: "/mnt/Mediafiles"
