- name: Create namespace for Longhorn
  kubernetes.core.k8s:
    state: present
    kind: Namespace
    name: longhorn-system
    kubeconfig: "{{ kubeconfig_path }}"

- name: Add Longhorn Helm repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
    kubeconfig: "{{ kubeconfig_path }}"

- name: Install or upgrade Longhorn via Helm
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: false
    wait: true
    timeout: 600s
    kubeconfig: "{{ kubeconfig_path }}"
